In [2]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [35]:
#the weeks refers to a dim and the products and the region .......the weeks contains the region and the region contains the product
sales_data=np.array([[[500,600,700]],[[100,300,200]],
                     [[500,600,700]],[[800,100,600]],
                     [[550,680,900]],[[600,700,330]]
                    ])
print(sales_data)
print(sales_data.shape)

                

[[[500 600 700]]

 [[100 300 200]]

 [[500 600 700]]

 [[800 100 600]]

 [[550 680 900]]

 [[600 700 330]]]
(6, 1, 3)


In [41]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [45]:
#how to make an array filled with zeros
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
#how to make an array filled with ones
ones=np.ones((4,5))
print(ones)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
#how to fill an array with range of values
rarray=np.arange(15)
print(rarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [55]:
#Creating an Array with a Range of Values and Specific Step Size
range_step=np.arange(0,20,2)
print(range_step)

[ 0  2  4  6  8 10 12 14 16 18]


In [60]:
lin_spacearray=np.linspace(0,100,5)
lin_spacearray

array([  0.,  25.,  50.,  75., 100.])

In [64]:
random_array=np.random.rand(3,4)
random_array


array([[1.81649848e-01, 6.08464708e-01, 1.05920314e-01, 7.65029697e-01],
       [5.45241648e-01, 5.58690725e-01, 2.05609616e-01, 9.92725771e-01],
       [9.17813996e-01, 5.21852749e-01, 9.40068777e-01, 2.74217647e-04]])

In [67]:
rando_int=np.random.randint(0,10,(3,3))
random_array


array([[1.81649848e-01, 6.08464708e-01, 1.05920314e-01, 7.65029697e-01],
       [5.45241648e-01, 5.58690725e-01, 2.05609616e-01, 9.92725771e-01],
       [9.17813996e-01, 5.21852749e-01, 9.40068777e-01, 2.74217647e-04]])

In [69]:
zeros.shape


(3, 3)

In [71]:
zeros.dtype

dtype('float64')

In [74]:
d1_array=np.array([1,2,3,4,5])
print(d1_array[0])
print(d1_array[-1])


1
5


In [77]:
print(d1_array[0:3])

[1 2 3]


In [84]:
d2_array=np.array([[1,2,3,4],[5,6,7,8]])
d2_array[1][0:2]


array([5, 6])

In [94]:
great_than_4=d2_array>4
d2_array[great_than_4]

array([5, 6, 7, 8])

In [96]:
#this is a broad casting
d2_array+10


array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [110]:
arr2=np.array([[1,2,3,20],[4,5,6,10]])
d2_array=np.array([[1,2,3,4],[5,6,7,3],[5,6,7,3],[5,6,7,3]])
print(np.dot(arr2,d2_array))



[[126 152 178  79]
 [109 134 159  79]]


In [115]:
print(arr2.mean())
print(d2_array.mean())


6.375
4.5625


In [120]:
#getting the man
print(arr2.max())
print(arr2.min())


20
1


In [123]:
m_array=np.array([1,2,3,4,5])
print(np.diag(m_array))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [126]:
#how to extract the diag from a matrix
print(np.diag(arr2))
print(arr2)

[1 5]
[[ 1  2  3 20]
 [ 4  5  6 10]]


In [133]:
#the identity matrix 
identity_mat=np.eye(10)
identity_mat

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [136]:
task_arr=np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15],
                   [16,17,18,19,20],
                   [21,22,23,24,25],
                   [26,27,28,29,30]])
print(task_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [144]:
zeros_array=np.zeros((6,5))
zeros_array[2:4,0:2]=task_arr[2:4,0:2]
zeros_array

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [11., 12.,  0.,  0.,  0.],
       [16., 17.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [153]:
zeros_array=np.zeros((6,5))
np.diag(task_arr)
zeros_array[0,0]=np.diag(task_arr)[0]
zeros_array[1,1]=np.diag(task_arr)[1]
zeros_array[2,2]=np.diag(task_arr)[2]
zeros_array[2,2]=np.diag(task_arr)[2]
zeros_array[3,3]=np.diag(task_arr)[3]
zeros_array[4,4]=np.diag(task_arr)[4]
print(zeros_array)





[[ 1.  0.  0.  0.  0.]
 [ 0.  7.  0.  0.  0.]
 [ 0.  0. 13.  0.  0.]
 [ 0.  0.  0. 19.  0.]
 [ 0.  0.  0.  0. 25.]
 [ 0.  0.  0.  0.  0.]]


In [155]:
zeros_array=np.zeros((6,5))
zeros_array[0,4:6]=task_arr


array([0.])